### PR TITLE
Move requirements to requirements.txt

### PR DESCRIPTION
**Pull request by jfchevrette**
See title

Also updated the cli description to match the description found in the readme

### CODE REVIEW

**Review by jmelis — COMMENTED** [review]
@jfchevrette Why don't you like install_requires? I prefer it over requirements.txt

**Comment by jfchevrette** [comment]
> @jfchevrette Why don't you like install_requires? I prefer it over requirements.txt

install_requires wasn't a valid parameter here. It looks like it is supported by setuptools and not distutils.

Another way to fix this might be to switch to setuptools rather than distutils?

I don't know which of requirements.txt and pip vs. setuptools is better. Maybe both are useful for different reasons?

**Comment by jmelis** [comment]
Ah yes, I had to do this:

```diff
diff --git a/bin/generate_report.py b/bin/generate_report.py
old mode 100644
new mode 100755
diff --git a/setup.py b/setup.py
index b341a61..cd274f8 100644
--- a/setup.py
+++ b/setup.py
@@ -1,4 +1,6 @@
-from distutils.core import setup
+from setuptools import setup
+
 
 setup(
     name='PagerDitty',
@@ -17,4 +19,4 @@ setup(
         "python-intervals >= 1.8.0",
         "python-dateutil >= 2.7.5",
     ],
-)
\ No newline at end of file
+)
```

I don't undertand why, though...

> I don't know which of requirements.txt and pip vs. setuptools is better. Maybe both are useful for different reasons?

Looking at [this](https://packaging.python.org/discussions/install-requires-vs-requirements/#requirements-files) __perhaps__ I understand that using `install_requires` is more appropriate for this use case, but not totally sure...

I'm asking mostly because all the `qontract` repos are using `setup.py` and not `requirements.txt`, and I'd like to agree on a single way to package python apps :)

**Comment by jmelis** [comment]
I just found this thread which is great: https://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing

**Comment by jakedt** [comment]
So where did this land? I was pretty sure that the way I did it was the right way for packges that can be used as binaries or libraries, but I'm definitely no packaging expert.

**Comment by jfchevrette** [comment]
I'm no packaging expert either & it seems to be building fine at the moment. Closing.

**Pull request closed without merging**
